# Generated by Django 3.2.3 on 2021-05-20 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=100)),
                ('store_address', models.TextField(null=True)),
                ('store_link', models.CharField(max_length=250)),
                ('status', models.SmallIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('store_seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.seller')),
            ],
            options={
                'db_table': 'tbl_store',
                'ordering': ['store_name'],
            },
        ),
    ]
