# Generated by Django 3.2.3 on 2021-05-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210521_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=250, null=True)),
                ('cust_address', models.TextField(null=True)),
                ('cust_mobile', models.CharField(max_length=100)),
                ('cust_otp', models.CharField(max_length=50)),
                ('cust_status', models.SmallIntegerField(default=1)),
                ('cust_created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_customer',
                'ordering': ['cust_name'],
            },
        ),
    ]
