# Generated by Django 3.2.3 on 2021-05-21 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('crt_order_id', models.IntegerField(default=0)),
                ('crt_user_id', models.IntegerField(default=None)),
                ('crt_token', models.IntegerField(default=None)),
                ('crt_prd_qty', models.IntegerField()),
                ('crt_prd_price', models.FloatField()),
                ('crt_prd_tot_price', models.FloatField()),
                ('prd_status', models.SmallIntegerField()),
                ('prd_created_on', models.DateTimeField(auto_now_add=True)),
                ('crt_prd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'db_table': 'tbl_cart',
                'ordering': ['prd_created_on'],
            },
        ),
    ]
