# Generated by Django 3.2.3 on 2021-05-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_crt_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['crt_prd_created_on']},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='prd_created_on',
            new_name='crt_prd_created_on',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='prd_status',
            new_name='crt_prd_status',
        ),
        migrations.AlterField(
            model_name='cart',
            name='crt_token',
            field=models.TextField(default=None, null=True),
        ),
    ]
