# Generated by Django 3.2.3 on 2021-05-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210521_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='crt_token',
            field=models.TextField(null=True),
        ),
    ]
