# Generated by Django 3.2.3 on 2021-05-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('ord_id', models.AutoField(primary_key=True, serialize=False)),
                ('ord_customer_id', models.IntegerField(default=0)),
                ('ord_total_amt', models.FloatField(default=None)),
                ('ord_status', models.SmallIntegerField(default=0)),
                ('ord_created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_orders',
                'ordering': ['ord_created_on'],
            },
        ),
    ]
