# Generated by Django 3.2.3 on 2021-05-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('prd_id', models.AutoField(primary_key=True, serialize=False)),
                ('prd_name', models.CharField(max_length=250)),
                ('prd_category', models.CharField(max_length=250)),
                ('prd_mrp_price', models.FloatField(null=True)),
                ('prd_sale_price', models.FloatField(null=True)),
                ('prd_desc', models.TextField()),
                ('prd_img', models.ImageField(upload_to='uploads/')),
                ('prd_store_link', models.CharField(max_length=100)),
                ('prd_status', models.SmallIntegerField()),
                ('prd_created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_product',
                'ordering': ['prd_name'],
            },
        ),
    ]
